// Full co-op flow through the real App: host -> join -> lobby -> garage (buy) -> run -> death -> results -> garage.
import { chromium } from 'playwright-core';
const BASE = process.env.BASE || 'http://localhost:5180';
const browser = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true, args: ['--use-angle=d3d11', '--force_high_performance_gpu', '--autoplay-policy=no-user-gesture-required', '--disable-background-timer-throttling', '--disable-renderer-backgrounding', '--disable-backgrounding-occluded-windows'] });
const mk = async (tag) => { const c = await browser.newContext({ viewport: { width: 1280, height: 720 } }); const p = await c.newPage(); p.on('pageerror', (e) => console.log(`[${tag} pageerror]`, e.message)); p.on('console', (m) => { if (m.type() === 'error' && !/404|GLB/.test(m.text())) console.log(`[${tag} err]`, m.text().slice(0, 200)); }); return p; };
const A = await mk('host'), B = await mk('guest');
const wait = (ms) => new Promise((r) => setTimeout(r, ms));
await A.goto(BASE + '/'); await B.goto(BASE + '/');
await A.waitForFunction('window.__app', null, { timeout: 60000 }); await B.waitForFunction('window.__app', null, { timeout: 60000 });
await A.evaluate('localStorage.clear(); window.__app.profile.cash = 5000; window.__app.host()');
await A.waitForFunction('window.__app.session && window.__app.session.code', null, { timeout: 30000 });
const code = await A.evaluate('window.__app.session.code'); console.log('room', code);
await B.evaluate((c) => window.__app.join(c), code);
await A.waitForFunction('window.__app.session.connected && window.__app.session.other', null, { timeout: 30000 });
await wait(800);
console.log('lobby host', await A.evaluate('JSON.stringify(window.__app._lobbyState())'));
await A.evaluate('window.__app.session.setReady(true)'); await B.evaluate('window.__app.session.setReady(true)');
await wait(800);
console.log('canStart', await A.evaluate('window.__app.session.canStart()'));
await A.screenshot({ path: 'shots/flow_lobby.png' });
await A.evaluate('window.__app._lobbyCb().onStart()');
await wait(1500);
console.log('modes', await A.evaluate('window.__game.mode'), await B.evaluate('window.__game.mode'));
// guest buys a weapon via the host
await B.evaluate("window.__app._garageCb().onBuy('weapon', 'revolver')");
await wait(800);
console.log('after buy: host cash', await A.evaluate('window.__app.profile.cash'), 'guest cash', await B.evaluate('window.__app.profile.cash'), 'guest weapons', await B.evaluate('Object.keys(window.__app.profile.weapons).join()'));
await B.screenshot({ path: 'shots/flow_garage_guest.png' });
await A.evaluate('window.__app._garageCb().onReady()'); await B.evaluate('window.__app._garageCb().onReady()');
await A.waitForFunction('window.__run && window.__run.sim', null, { timeout: 60000 });
await B.waitForFunction('window.__run', null, { timeout: 60000 });
await A.evaluate('window.__autodrive = { speed: 30 }'); await B.evaluate('window.__aimbot = true');
await wait(15000);
console.log('run host', await A.evaluate('JSON.stringify({s: window.__run.player.s|0, state: window.__run.sim.state, kills: window.__run.sim.stats.kills, cash: window.__run.cash})'));
console.log('run guest', await B.evaluate('JSON.stringify({s: window.__run.playerS|0, states: window.__run.states.size, shots: window.__run.shots, hits: window.__run.hitsLanded})'));
await B.screenshot({ path: 'shots/flow_run_gunner.png' });
await A.evaluate('window.__run.sim.explodeCar(window.__run.player, "test", -1)');
await wait(9500);
console.log('after death modes', await A.evaluate('window.__game.mode + " " + (document.querySelector(".results") ? "results" : "noresults")'), await B.evaluate('window.__game.mode + " " + (document.querySelector(".results") ? "results" : "noresults")'));
await B.screenshot({ path: 'shots/flow_results_guest.png' });
console.log('profile runs host/guest', await A.evaluate('window.__app.profile.runs + " $" + window.__app.profile.cash'), await B.evaluate('window.__app.profile.runs + " $" + window.__app.profile.cash'));
await browser.close();
