"""Generate public/models/weapons/README.md from the GLBs + tools/blender/weapons/notes/*.json (written by Gun.finish()).
Run with the system python:  python tools/blender/weapons/make_readme.py"""
import json, os, struct, glob, math

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
WDIR = os.path.join(ROOT, "public", "models", "weapons")
NDIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "notes")
ORDER = ["pistol", "revolver", "smg", "shotgun", "rifle", "lmg", "sniper", "rpg", "grenade", "rocket", "shell_9mm", "shell_shotgun", "shell_rifle"]
TITLES = {
    "pistol": "9 mm semi-auto pistol", "revolver": ".357 revolver", "smg": "compact 9 mm SMG", "shotgun": "12 ga pump shotgun",
    "rifle": "assault rifle (AK/M4 hybrid)", "lmg": "belt-fed light machine gun", "sniper": "bolt-action sniper rifle", "rpg": "RPG launcher",
    "grenade": "frag grenade", "rocket": "RPG rocket (projectile)", "shell_9mm": "9 mm casing", "shell_shotgun": "12 ga shell", "shell_rifle": "rifle casing",
}


def read_glb(path):
    b = open(path, "rb").read()
    l = struct.unpack("<I", b[12:16])[0]
    return json.loads(b[20:20 + l])


def node_tree(j):
    nodes = j["nodes"]
    parent = {}
    for i, n in enumerate(nodes):
        for c in n.get("children", []):
            parent[c] = i
    def world_t(i):
        t = list(nodes[i].get("translation", [0, 0, 0]))
        p = parent.get(i)
        while p is not None:
            pt = nodes[p].get("translation", [0, 0, 0])
            t = [t[k] + pt[k] for k in range(3)]
            p = parent.get(p)
        return t
    return nodes, parent, world_t


def bbox(j):
    nodes, parent, world_t = node_tree(j)
    lo = [1e9] * 3; hi = [-1e9] * 3
    for i, n in enumerate(nodes):
        if "mesh" in n:
            t = world_t(i)
            for pr in j["meshes"][n["mesh"]]["primitives"]:
                a = j["accessors"][pr["attributes"]["POSITION"]]
                for k in range(3):
                    lo[k] = min(lo[k], a["min"][k] + t[k]); hi[k] = max(hi[k], a["max"][k] + t[k])
    return lo, hi


def fmt(v):
    return "(" + ", ".join("%.3f" % x for x in v) + ")"


SOCKETS = ["muzzle", "eject", "grip_R", "grip_L", "mag_well", "sight", "stock"]

out = []
out.append("""# Weapon models (`public/models/weapons/*.glb`)

Generated by the headless-Blender scripts in `tools/blender/weapons/` (`gunlib.py` = modelling helpers, `gunfinish.py`/`gunlook.py` = texture baking; one script per weapon).
Rebuild one: `"C:/Dev/tools/Blender-4.5.11-portable/blender.exe" -b --factory-startup -P tools/blender/weapons/<gun>.py -- --size 2048` (add `--flat` for a fast untextured export).
This README is regenerated by `python tools/blender/weapons/make_readme.py`.

## Conventions (all weapons)
- glTF frame, metres, 1:1 scale. **Muzzle faces +Z**, +Y up, +X = the weapon's LEFT (right side = -X). Origin = pistol-grip centre (where the right palm sits) for guns; body centre for grenade; see per-item notes.
- Every moving part is a separate node with its **origin at its pivot**; child nodes (e.g. `bolt_handle` under `bolt`) move with their parent. Position/rotation values below are given in that node's *local* glTF axes.
- Sockets are empties (Object3D). Their +Z is forward, +Y up, except `eject`, which is rotated 180 deg about Y so that **its local +X is the case ejection direction** (the weapon's right side, i.e. world -X for a right-eject gun). Positions are in metres relative to the model origin.
- Materials (names are the contract): `gun_metal` (blued steel), `gun_black` (black oxide/coated), `gun_steel` (bright steel), `polymer`, `wood`, `rubber`, `brass`, `glass_lens` (transparent, not textured), `paint`/`paint2` where painted parts exist. Each gun has ONE texture atlas (baseColor JPEG + ORM JPEG (R=AO, G=roughness, B=metal) + normal PNG) shared by all its materials; the materials only differ by name (and a sub-1% base-colour tint factor so glTF keeps them distinct). The game may swap/tint materials by name (e.g. `material.color` on `polymer`).
- Textures carry edge wear, scratches, grime, oil sheen, stipple/wood grain baked from the geometry (AO + convex-edge masks), so they only make sense on the unmodified mesh. VRAM: each 2048 atlas = 3 maps (~64 MB with mips); small items use 512-1024.
- `mag` is always a complete detailed part (rounds visible in feed lips / windows / belt) whose origin is where it seats; `mag_well` socket sits at the same point.

## Animation guide
For each moving node the table gives `kind`: **translate** = offset along a local axis (mm); **rotate** = angle about a local axis through the node origin (right-hand rule, degrees). The rest pose in the file is the *ready* pose (slide/bolt closed, cover shut, mag seated) unless noted.
""")

for name in ORDER:
    gp = os.path.join(WDIR, name + ".glb")
    if not os.path.exists(gp):
        out.append("\n## %s\n\n(not built yet)\n" % name)
        continue
    j = read_glb(gp)
    nodes, parent, world_t = node_tree(j)
    lo, hi = bbox(j)
    notes = {}
    npath = os.path.join(NDIR, name + ".json")
    if os.path.exists(npath):
        notes = json.load(open(npath))
    tris = notes.get("tris")
    kb = round(os.path.getsize(gp) / 1024)
    mats = [m["name"] for m in j.get("materials", [])]
    imgs = j.get("images", [])
    out.append("\n---\n\n## `%s.glb` - %s\n" % (name, TITLES.get(name, name)))
    out.append("- **Triangles:** %s   **File:** %d KB   **Materials:** %s" % (tris if tris else "?", kb, ", ".join("`%s`" % m for m in mats)))
    out.append("- **Bounding box (m):** x %.3f..%.3f (width %.3f), y %.3f..%.3f (height %.3f), z %.3f..%.3f (**length %.3f**)" % (lo[0], hi[0], hi[0] - lo[0], lo[1], hi[1], hi[1] - lo[1], lo[2], hi[2], hi[2] - lo[2]))
    if imgs:
        out.append("- **Textures:** " + ", ".join("%s (%s)" % (i.get("name", "?"), i.get("mimeType", "?").split("/")[-1]) for i in imgs))
    sock = [(i, n) for i, n in enumerate(nodes) if "mesh" not in n and not n.get("children") and n["name"] in SOCKETS + ["throw", "flame_origin", "eject_dir", "rocket_tip"]]
    extra_sock = [(i, n) for i, n in enumerate(nodes) if "mesh" not in n and not n.get("children") and (i, n) not in sock]
    out.append("\n**Nodes** (pivot = node origin, metres in model space):\n")
    out.append("| node | pivot (x left, y up, z fwd) | parent | notes |")
    out.append("|---|---|---|---|")
    for i, n in enumerate(nodes):
        if "mesh" not in n:
            continue
        p = parent.get(i)
        pn = nodes[p]["name"] if p is not None else "-"
        mv = [m for m in notes.get("motions", []) if m["node"] == n["name"]]
        tag = "moving" if mv else "static"
        out.append("| `%s` | %s | %s | %s |" % (n["name"], fmt(world_t(i)), pn, tag))
    out.append("\n**Sockets:**\n")
    out.append("| socket | position (m) | local orientation |")
    out.append("|---|---|---|")
    for i, n in sorted(sock + extra_sock, key=lambda t: t[1]["name"]):
        rot = n.get("rotation")
        o = "+Z forward, +Y up"
        if rot and abs(rot[3]) < 0.999:
            o = "rotated (quat %s): see note" % fmt(rot)
        if n["name"] == "eject":
            o = "**+X = ejection direction** (rotated 180 deg about Y)"
        out.append("| `%s` | %s | %s |" % (n["name"], fmt(world_t(i)), o))
    if notes.get("motions"):
        out.append("\n**Moving parts:**\n")
        out.append("| node | kind | local axis (glTF) | amount | how |")
        out.append("|---|---|---|---|---|")
        for m in notes["motions"]:
            unit = "mm" if m["kind"] == "translate" else "deg"
            out.append("| `%s` | %s | %s | %g %s | %s |" % (m["node"], m["kind"], fmt(m["axis_gltf"]), m["amount"], unit, m["note"]))
    if notes.get("remarks"):
        out.append("\n**Notes:**\n")
        for r in notes["remarks"]:
            out.append("- " + r)

open(os.path.join(WDIR, "README.md"), "w", encoding="utf-8").write("\n".join(out) + "\n")
print("wrote README.md")
