"""docs_gen.py - writes docs/AUDIO_LIST.md from public/audio/manifest.json (run after manifest.py)."""
import json
import os
import sys

import render as R
import manifest as M

DOC = os.path.join(R.ROOT, "docs", "AUDIO_LIST.md")

GROUP_TITLES = [
    ("guns", "GUNS - fire, reloads, grenades, shells"),
    ("impacts", "IMPACTS - bullets, near-misses, hit feedback, car damage"),
    ("explosions", "EXPLOSIONS - blasts, fire, shockwave"),
    ("vehicles", "VEHICLES - engines, forced induction, tyres, wind, misc"),
    ("ui", "UI"),
    ("stingers", "STINGERS"),
    ("ambience", "AMBIENCE"),
    ("music", "MUSIC"),
]


def fmt_loop(d):
    return "LOOP" if d["loop"] else "one-shot"


def main():
    man = M.build_manifest()
    S = man["sounds"]
    L = []
    L.append("# RIDE OR DIE - audio library")
    L.append("")
    L.append("Generated by `tools/audio` (Python synthesis + CC0 Kenney / rubberduck sample layers), encoded Ogg Vorbis q5 (ambience q4), 44.1 kHz.")
    L.append(f"{len(S)} sound entries, {sum(d['variations'] for d in S.values())} files, {man['totalBytes'] / 1e6:.1f} MB. "
             "Machine-readable index: `public/audio/manifest.json` (rebuilt by `tools/audio/manifest.py`).")
    L.append("")
    L.append("## Loudness / usage conventions")
    L.append("- **Peak**: every decoded file peaks at or below -1 dBFS, no clipping, no DC. One-shots are peak-normalised (about -1.5 dBFS); "
             "loops (engines, tyres, wind, ambience, alerts) are normalised by integrated LUFS (K-weighted) so they can be crossfaded / layered.")
    L.append("- **`gain`** in the manifest is a linear multiplier <= 1.0 that balances loudness inside each category (variations of one sound are already "
             "matched to each other in the files) and gives sensible cross-category defaults (explosions/guns loud, foley/UI/ambience lower). "
             "Multiply by your bus volume (SFX bus ~0.8, engine bus ~0.6, ambience ~0.5, music ~0.6 are good starting points).")
    L.append("- **Variations**: `files[]` lists variation files (`name_1.ogg`, `name_2.ogg` ...). Pick randomly, never the same twice in a row, and add +-`pitchRange` "
             "playbackRate jitter. Multi-variation sets were loudness-matched (+-0.2 LU).")
    L.append("- **Loops** have `loop: true`, `loopStart: 0`, `loopEnd: duration`. They are exact-length seamless loops (built from periodic noise / integer engine cycles; "
             "wrap step checked against the interior step distribution in `tools/audio/qa_all.py`). Use `AudioBufferSourceNode.loop = true`.")
    L.append("- **Mono** for positional SFX (feed into PannerNode), **stereo** for ambience, music, stingers.")
    L.append("- Rendering is deterministic (seeded); re-run `tools/audio/venv/Scripts/python.exe tools/audio/build.py <group>` to regenerate.")
    L.append("")
    L.append("### Engine stages (vehicles/engine_*)")
    L.append("Each engine has 5 seamless loops recorded at a fixed RPM (`idle, low, mid, high, redline`). Keep 1-2 stages playing at once: "
             "crossfade the two neighbouring stages with equal-power gains by RPM, and set `playbackRate = currentRPM / stageRPM` "
             "(stay within 0.75-1.35 of each stage's nominal). `fireHz` is the cylinder-firing frequency at the nominal RPM "
             "(engine fundamental, verified by spectrum analysis in `qa_engines.py`). Layer `turbo_whine_loop` / `supercharger_whine_loop` "
             "(reference pitch 3.3 kHz / 1.5 kHz, playbackRate 0.5-1.6, gain rising with boost/RPM) on t4 / boss; "
             "`damaged_engine_loop` overlays at low HP.")
    L.append("")
    L.append("| engine | character | cyl | stage | RPM | fireHz | file | dur (s) |")
    L.append("|---|---|---|---|---|---|---|---|")
    for name, e in man["engines"].items():
        for st in e["stages"]:
            L.append(f"| {name} | {e['description']} | {S['vehicles/' + name + '_' + st['stage']]['cylinders']} | {st['stage']} | {st['rpm']} | {st['fireHz']} | "
                     f"`{st['file']}` | {st['duration']:.2f} |")
    L.append("")
    L.append("### Suggested pitch (playbackRate) ranges")
    L.append("| category | range |")
    L.append("|---|---|")
    for c, pr in M.PITCH.items():
        L.append(f"| {c} | {pr[0]:.2f} - {pr[1]:.2f} |")
    L.append("")
    for g, title in GROUP_TITLES:
        items = [(k, d) for k, d in S.items() if k.startswith(g + "/")]
        if not items:
            continue
        L.append(f"## {title}")
        L.append("")
        L.append("| sound | var | dur (s) | type | gain | pitch | category | notes |")
        L.append("|---|---|---|---|---|---|---|---|")
        for k, d in items:
            if "engine" in d and "stage" in d:
                continue
            dur = f"{d['duration']:.2f}" if d["variations"] == 1 else f"{min(d['durations']):.2f}-{max(d['durations']):.2f}"
            L.append(f"| `{k}` | {d['variations']} | {dur} | {fmt_loop(d)} | {d['gain']:.2f} | {d['pitchRange'][0]:.2f}-{d['pitchRange'][1]:.2f} | {d['category']} | {d['notes']} |")
        L.append("")
    os.makedirs(os.path.dirname(DOC), exist_ok=True)
    with open(DOC, "w", encoding="utf8") as f:
        f.write("\n".join(L) + "\n")
    print("wrote", DOC, len(L), "lines")


if __name__ == "__main__":
    main()
